theme = 'awesome-identity'
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Pedro Lobato'

## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.png"
  firstname = "Pedro"
  lastname = "Lobato"
  title = "Software Engineer / Developer"
  bio = """ Hey there, what are you looking for? """


## Footer Configurations
##[params.footer]
##  copyright = "© 2020-2024 Byungjin Park. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
##  poweredBy = true
